"""Output formatting for omen: JSON and H1-flavored markdown.

JSON is the machine-readable contract. H1-markdown produces a report body
shaped for a HackerOne submission: title, severity, summary, evidence, and
remediation per finding.
"""

from __future__ import annotations

import json

from .analyzer import AnalysisReport
from .findings import Finding


def to_json(report: AnalysisReport, *, indent: int = 2) -> str:
    return json.dumps(report.to_dict(), indent=indent, sort_keys=False)


_REMEDIATION = {
    "prodigal": (
        "Add access control (e.g. an owner check or role guard) to any "
        "function that sends Ether, and validate the destination."
    ),
    "suicidal": (
        "Restrict selfdestruct to an authorized owner, or remove it. "
        "Prefer a pausable/upgradeable pattern over destruction."
    ),
    "greedy": (
        "Add a withdraw path so deposited Ether can be released, or make "
        "the contract non-payable if it is not meant to hold funds."
    ),
    "reentrancy": (
        "Apply checks-effects-interactions: update state before the external "
        "call, or use a reentrancy guard (e.g. OpenZeppelin ReentrancyGuard)."
    ),
    "access-control": (
        "Restrict privileged functions and protected state with an explicit "
        "access guard (e.g. an `onlyOwner` modifier or OpenZeppelin "
        "AccessControl roles), and emit an event whenever ownership or a role "
        "changes so off-chain monitors can detect unauthorized changes."
    ),
    "tx-origin": (
        "Never use `tx.origin` for authorization — it is the original external "
        "account, not the immediate caller, so an attacker contract a victim "
        "interacts with can act on the victim's behalf. Use `msg.sender` "
        "instead (and a role/owner check on top of it)."
    ),
}


def _finding_md(index: int, f: Finding) -> str:
    lines: list[str] = []
    lines.append(f"### {index}. {f.title}")
    lines.append("")
    lines.append(f"- **Category:** {f.category}")
    lines.append(f"- **Severity:** {f.severity.value}")
    lines.append(f"- **Confidence:** {f.confidence}")
    if f.contract:
        lines.append(f"- **Contract:** `{f.contract}`")
    lines.append(f"- **Detector:** `{f.detector}`")
    lines.append("")
    lines.append("**Summary**")
    lines.append("")
    lines.append(f.description or "(no description)")
    lines.append("")

    ev = f.evidence
    if ev.source_mapping or ev.opcodes or ev.trace:
        lines.append("**Evidence**")
        lines.append("")
        for loc in ev.source_mapping:
            lines.append(f"- source: `{loc}`")
        for op in ev.opcodes:
            lines.append(
                f"- opcode: `{op.get('opcode')}` at offset "
                f"`0x{op.get('offset', 0):x}`"
            )
        if ev.calldata:
            lines.append(f"- calldata: `{ev.calldata}`")
        if ev.expected_outcome:
            lines.append(f"- expected outcome: {ev.expected_outcome}")
        for step in ev.trace:
            lines.append(f"- trace: `{step}`")
        lines.append("")

    lines.append("**Remediation**")
    lines.append("")
    lines.append(_REMEDIATION.get(f.category, "Review and remediate the issue."))
    lines.append("")
    return "\n".join(lines)


def to_h1md(report: AnalysisReport) -> str:
    lines: list[str] = []
    lines.append(f"# omen report — {report.origin}")
    lines.append("")
    lines.append(f"- **Tool:** {report.tool} v{report.version}")
    lines.append(f"- **Input type:** {report.input_type}")
    lines.append(f"- **Checks run:** {', '.join(report.checks)}")
    lines.append(f"- **Findings:** {len(report.findings)}")
    lines.append("")

    if not report.findings:
        lines.append("No findings for the requested checks.")
        lines.append("")
    else:
        lines.append("## Findings")
        lines.append("")
        for i, f in enumerate(report.findings, start=1):
            lines.append(_finding_md(i, f))

    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by omen. For authorized security testing only. "
        "omen performs analysis only and never submits transactions._"
    )
    lines.append("")
    return "\n".join(lines)


def render(report: AnalysisReport, fmt: str) -> str:
    if fmt == "json":
        return to_json(report)
    if fmt == "h1md":
        return to_h1md(report)
    raise ValueError(f"unknown output format: {fmt}")
